import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faFacebook,
  faTwitter,
  faYoutube,
  faInstagram,
} from '@fortawesome/free-brands-svg-icons';
import {
  faBars,
  faTimes,
  faSquare,
  faCircleCheck,
  faSquareCheck,
  faTrashAlt,
  faPenToSquare,
  faBugs,
  faExclamationCircle,
  faPlus,
  faUpload,
  faDownload,
  faFilter,
  faCircleXmark,
  faSort,
  faCaretUp,
  faCaretDown,
  faCaretRight,
  faArrowLeft,
  faArrowRight,
  faFloppyDisk,
  faFileExport,
  faSpinner,
  faWallet,
  faXmarksLines,
  faFireFlameCurved,
  faTree,
  faSkullCrossbones,
  faCircleInfo,
  faRadiation,
  faTriangleExclamation,
  faBullhorn,
  faStickyNote,
  faMagnifyingGlass,
  faPaperPlane,
  faCircleDot,
  faCircle,
} from '@fortawesome/free-solid-svg-icons';
import { faShop } from '@fortawesome/free-solid-svg-icons/faShop';

library.add(
  faBars,
  faFacebook,
  faTwitter,
  faYoutube,
  faInstagram,
  faTimes,
  faSquare,
  faCircleCheck,
  faCircleDot,
  faCircle,
  faSquareCheck,
  faTrashAlt,
  faPenToSquare,
  faBugs,
  faExclamationCircle,
  faPlus,
  faUpload,
  faDownload,
  faFilter,
  faCircleXmark,
  faSort,
  faCaretUp,
  faCaretDown,
  faCaretRight,
  faArrowLeft,
  faArrowRight,
  faFloppyDisk,
  faFileExport,
  faSpinner,
  faWallet,
  faXmarksLines,
  faFireFlameCurved,
  faTree,
  faShop,
  faSkullCrossbones,
  faCircleInfo,
  faRadiation,
  faTriangleExclamation,
  faBullhorn,
  faStickyNote,
  faMagnifyingGlass,
  faPaperPlane,
);

export default FontAwesomeIcon;
